version: "3"

services:
  mysql:
    image: mysql:latest
    container_name: mysql_server
    ports:
      - "3306:3306"
    cap_add:
      - SYS_NICE
    environment:
      MYSQL_ROOT_PASSWORD: s3cr37
      MYSQL_USER: db_user
      MYSQL_PASSWORD: s3cr37
      MYSQL_DATABASE: MyDB